### ISSUE TITLE
Panics when attempting to list activity for a Board that does not exist

### ISSUE THREAD

**Issue by lanzafame** [klauern/trackello#1]
I made an error putting my board id into the config file and when I attempted to run the `trackello list` command I received the following panic:
```go
Using config file: /Users/adrianlanzafame/.trackello.yaml
Printing Board activity for Board ID <insert wrong id here>
panic: Error retrieving Board ID '<insert wrong id here>': Received unexpected status 404 while trying to retrieve the server data with "The requested resource was not found."

goroutine 1 [running]:
github.com/klauern/trackello/cmd.PrintParallelBoardActivity(0xc4200c76a0, 0x18)
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/cmd/list.go:65 +0x10c
github.com/klauern/trackello/cmd.ListActivity(0x1695800, 0x16b7f80, 0x0, 0x0)
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/cmd/list.go:47 +0x1df
github.com/klauern/trackello/vendor/github.com/spf13/cobra.(*Command).execute(0x1695800, 0x16b7f80, 0x0, 0x0, 0x1695800, 0x16b7f80)
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/klauern/trackello/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1695a20, 0xc420072058, 0x0, 0x16)
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/klauern/trackello/vendor/github.com/spf13/cobra.(*Command).Execute(0x1695a20, 0x1695a20, 0xc4200f5f50)
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/klauern/trackello/cmd.Execute()
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/cmd/root.go:37 +0x31
main.main()
	/Users/adrianlanzafame/dev/src/github.com/klauern/trackello/cmd/trackello/main.go:22 +0x20
```

Obviously, you can't fix my user error but an error message saying that the board doesn't exist would be preferable to a panic stack trace 😄 . Otherwise, great project, cheers 👍

**Comment by klauern** [comment]
Hi @lanzafame!

I think I got it fixed.  I had been neglecting this for a bit, so I appreciate the nudge.  Let me know if this improves things for you.
